import crypto from 'node:crypto';

const redirects={
  '/servicedesk':'http://renpsg.atlassian.net/servicedesk/customer/portal/2',
  '/changerequest':'http://renpsg.atlassian.net/servicedesk/customer/portal/5',
  '/google':'https://google.com',
  '/myapps':'https://myapplications.office.com',
  '/lsps':'https://fivem-lsps-portal.vercel.app/'
};
const REQUESTS='website_requests';
const USERS='admin_users';
const STATUSES=['New','Contacted','Quoted','In Progress','Completed','Declined'];
const ROLES=['owner','admin','viewer'];
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function send(res,status,type,body,headers={}){res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store',...headers});res.end(body)}
const sendJson=(res,status,data)=>send(res,status,'application/json; charset=utf-8',JSON.stringify(data));
async function body(req){let raw='';for await(const c of req){raw+=c;if(raw.length>100000)throw Error('Request too large')}if(!raw)return{};return(req.headers['content-type']||'').includes('json')?JSON.parse(raw):Object.fromEntries(new URLSearchParams(raw))}
function cfg(){if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw Error('Supabase is not configured');return{url:process.env.SUPABASE_URL.replace(/\/$/,''),key:process.env.SUPABASE_SERVICE_ROLE_KEY}}
async function db(path,method='GET',payload,headers={}){const{url,key}=cfg();const r=await fetch(url+'/rest/v1/'+path,{method,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',Prefer:'return=representation',...headers},body:payload?JSON.stringify(payload):undefined});const t=await r.text();let data=null;try{data=t?JSON.parse(t):null}catch{data=t||null}if(!r.ok)throw Error(data?.message||data?.error||'Database request failed');return{data,headers:r.headers}}
function secret(){return process.env.ADMIN_SESSION_SECRET||''}
function makeToken(user){const payload=Buffer.from(JSON.stringify({id:user.id,username:user.username,display_name:user.display_name,role:user.role,exp:Date.now()+43200000})).toString('base64url');const sig=crypto.createHmac('sha256',secret()).update(payload).digest('base64url');return payload+'.'+sig}
function session(req){const value=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('talondns_admin='))?.slice(15);if(!value||!secret())return null;const[payload,sig]=value.split('.');if(!payload||!sig)return null;const expected=crypto.createHmac('sha256',secret()).update(payload).digest('base64url');try{if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const data=JSON.parse(Buffer.from(payload,'base64url').toString());return data.exp>Date.now()?data:null}catch{return null}}
const canEdit=u=>u&&['owner','admin'].includes(u.role);
const isOwner=u=>u?.role==='owner';

const baseCss=`:root{color-scheme:dark;--panel:#0d1c30;--line:#29415e;--text:#f4f8ff;--muted:#aebfd3}*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:var(--text);background:linear-gradient(150deg,#040912,#081524 52%,#050b14)}.shell,.admin{width:min(1180px,calc(100% - 32px));margin:auto}header{min-height:82px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.brand{color:inherit;text-decoration:none;font-weight:850}.brand small{display:block;color:var(--muted)}.cta,button{min-height:44px;display:inline-flex;align-items:center;justify-content:center;padding:0 18px;border:0;border-radius:11px;color:#03101c;background:#42c7ff;font:inherit;font-weight:850;text-decoration:none;cursor:pointer}.hero{display:grid;grid-template-columns:1fr 1fr;gap:40px;padding:60px 0}.lead,.meta,.fine{color:var(--muted)}h1{font-size:clamp(2.5rem,6vw,5rem);line-height:1}.card,.request,.usercard{padding:24px;border:1px solid var(--line);border-radius:18px;background:var(--panel)}form{display:grid;gap:14px}.row,.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}label{display:grid;gap:7px}input,select,textarea{width:100%;min-height:46px;padding:11px 13px;border:1px solid #36516f;border-radius:10px;color:white;background:#030c17;font:inherit}textarea{min-height:110px}.status{display:none;padding:12px;border-radius:10px}.status.ok{display:block;background:#74e3a314}.status.error{display:block;background:#ff505014}.grid{display:grid;gap:14px;padding:24px 0}.top{display:flex;justify-content:space-between;gap:12px;align-items:start}.field{padding:10px;border-radius:9px;background:#081524}.field strong{display:block;color:#8ba4bd;font-size:.72rem;text-transform:uppercase}.toolbar{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.tabs{display:flex;gap:8px;margin:20px 0}.tab{background:#152b45;color:white}.hidden{display:none}.danger{background:#ff6b6b}.login{width:min(430px,calc(100% - 32px));margin:12vh auto}@media(max-width:800px){.hero,.row,.fields{grid-template-columns:1fr}}`;
function publicPage(){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TalonDNS</title><style>${baseCss}</style></head><body><div class="shell"><header><a class="brand" href="/">TalonDNS<small>FiveM business web services</small></a><a class="cta" href="#register">Request service</a></header><main><section class="hero"><div><h1>Your business deserves a real online presence.</h1><p class="lead">Get a TalonDNS redirect, connect a custom domain, or request a complete FiveM business website and admin portal.</p></div><div class="card" id="register"><h2>Request web services</h2><form id="request"><div class="row"><label>Character name<input name="character_name" required></label><label>State ID<input name="state_id" required></label></div><div class="row"><label>Discord username<input name="discord_username" required></label><label>FiveM server<input name="fivem_server" required></label></div><label>Business name<input name="business_name" required></label><label>Service requested<select name="service_type" required><option value="">Select</option><option>TalonDNS redirect</option><option>Custom domain connection</option><option>Custom website design</option><option>Custom website with backend</option><option>Website design, hosting, and domain</option><option>Not sure yet</option></select></label><div class="row"><label>Requested short link<input name="requested_slug"></label><label>Custom domain<input name="custom_domain"></label></div><label>Existing website URL<input type="url" name="existing_website"></label><label>Features needed<input name="feature_package"></label><label>Project details<textarea name="project_details" required></textarea></label><div id="status" class="status"></div><button>Submit request</button></form></div></section></main></div><script>const f=document.getElementById('request'),s=document.getElementById('status');f.addEventListener('submit',async e=>{e.preventDefault();try{const r=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(f)))}),d=await r.json();if(!r.ok)throw Error(d.error);s.className='status ok';s.textContent='Request submitted. Reference: '+d.reference;f.reset()}catch(x){s.className='status error';s.textContent=x.message||'Unable to submit'}})</script></body></html>`}
function loginPage(err=''){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Login</title><style>${baseCss}</style></head><body><form class="card login" method="post" action="/admin/login"><h2>TalonDNS Admin</h2><p class="meta">Sign in with your individual account.</p>${err?`<p style="color:#ffb4b4">${esc(err)}</p>`:''}<label>Username<input name="username" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button>Sign in</button></form></body></html>`}
function adminPage(user){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TalonDNS Admin</title><style>${baseCss}</style></head><body><div class="admin"><header><div><h2>TalonDNS Admin</h2><div class="meta">Signed in as ${esc(user.display_name||user.username)} · ${esc(user.role)}</div></div><div class="toolbar"><button id="refreshRequests">Refresh</button><a href="/admin/logout" style="color:#9edfff">Sign out</a></div></header><div class="tabs"><button class="tab" data-tab="requests">Requests</button>${isOwner(user)?`<button class="tab" data-tab="users">Users</button>`:''}</div><main id="requestsTab"><div id="requests" class="grid">Loading...</div></main>${isOwner(user)?`<main id="usersTab" class="hidden"><section class="card"><h3>Add admin user</h3><form id="newUser"><div class="row"><label>Display name<input name="display_name" required></label><label>Username<input name="username" required></label></div><div class="row"><label>Password<input type="password" name="password" minlength="12" required></label><label>Role<select name="role"><option value="viewer">Viewer</option><option value="admin">Admin</option><option value="owner">Owner</option></select></label></div><button>Create user</button><div id="userStatus" class="status"></div></form></section><div id="users" class="grid"></div></main>`:''}</div><script>
const currentRole=${JSON.stringify(user.role)},statuses=${JSON.stringify(STATUSES)};
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function showTab(name){document.getElementById('requestsTab').classList.toggle('hidden',name!=='requests');const u=document.getElementById('usersTab');if(u)u.classList.toggle('hidden',name!=='users');if(name==='users')loadUsers()}
async function loadRequests(){const list=document.getElementById('requests');list.innerHTML='Loading...';try{const r=await fetch('/api/admin/requests',{credentials:'same-origin'});if(r.status===401){location='/admin';return}const a=await r.json();if(!r.ok)throw Error(a.error||'Unable to load requests');if(!Array.isArray(a))throw Error('The server returned an invalid response');if(!a.length){list.innerHTML='<p>No requests submitted.</p>';return}list.innerHTML=a.map(x=>{const options=statuses.map(s=>'<option '+(x.status===s?'selected':'')+'>'+h(s)+'</option>').join('');const control=currentRole==='viewer'?h(x.status):'<select class="request-status" data-id="'+h(x.id)+'">'+options+'</select>';return '<article class="request"><div class="top"><div><h2>'+h(x.business_name)+'</h2><div class="meta">'+h(x.reference)+' · '+new Date(x.created_at).toLocaleString()+'</div></div>'+control+'</div><div class="fields"><div class="field"><strong>Character</strong>'+h(x.character_name)+' ('+h(x.state_id)+')</div><div class="field"><strong>Discord</strong>'+h(x.discord_username)+'</div><div class="field"><strong>Server</strong>'+h(x.fivem_server)+'</div><div class="field"><strong>Service</strong>'+h(x.service_type)+'</div><div class="field"><strong>Short Link</strong>'+(h(x.requested_slug)||'—')+'</div><div class="field"><strong>Domain</strong>'+(h(x.custom_domain)||'—')+'</div></div><p>'+h(x.project_details)+'</p></article>'}).join('');document.querySelectorAll('.request-status').forEach(el=>el.addEventListener('change',()=>setStatus(el.dataset.id,el.value)))}catch(e){console.error(e);list.innerHTML='<p style="color:#ffb4b4">'+h(e.message||'Unable to load requests')+'</p>'}}
async function setStatus(id,status){const r=await fetch('/api/admin/requests/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(!r.ok)alert((await r.json()).error||'Unable to update')}
async function loadUsers(){const target=document.getElementById('users');if(!target)return;const r=await fetch('/api/admin/users');if(!r.ok)return;const a=await r.json();target.innerHTML=a.map(x=>'<article class="usercard"><div class="top"><div><strong>'+h(x.display_name)+'</strong><div class="meta">'+h(x.username)+' · '+h(x.role)+' · '+(x.active?'Active':'Disabled')+'</div></div><button class="toggle-user '+(x.active?'danger':'')+'" data-id="'+h(x.id)+'" data-active="'+String(!x.active)+'">'+(x.active?'Disable':'Enable')+'</button></div></article>').join('');target.querySelectorAll('.toggle-user').forEach(el=>el.addEventListener('click',()=>toggleUser(el.dataset.id,el.dataset.active==='true')))}
async function toggleUser(id,active){const r=await fetch('/api/admin/users/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({active})});if(!r.ok)alert((await r.json()).error||'Unable to update');else loadUsers()}
document.getElementById('refreshRequests').addEventListener('click',loadRequests);document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>showTab(el.dataset.tab)));const nf=document.getElementById('newUser');if(nf)nf.addEventListener('submit',async e=>{e.preventDefault();const s=document.getElementById('userStatus');const r=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(nf)))}),d=await r.json();s.className='status '+(r.ok?'ok':'error');s.textContent=r.ok?'User created':d.error;if(r.ok){nf.reset();loadUsers()}});loadRequests();
</script></body></html>`}
async function createRequest(req,res){try{const d=await body(req),required=['character_name','state_id','discord_username','fivem_server','business_name','service_type','project_details'];for(const k of required)if(!String(d[k]||'').trim())return sendJson(res,400,{error:'Missing '+k.replaceAll('_',' ')});const reference='TD-'+new Date().getFullYear()+'-'+crypto.randomBytes(3).toString('hex').toUpperCase();await db(REQUESTS,'POST',{reference,character_name:String(d.character_name).trim().slice(0,100),state_id:String(d.state_id).trim().slice(0,50),discord_username:String(d.discord_username).trim().slice(0,100),fivem_server:String(d.fivem_server).trim().slice(0,120),business_name:String(d.business_name).trim().slice(0,150),service_type:String(d.service_type).trim().slice(0,100),requested_slug:String(d.requested_slug||'').trim().toLowerCase().replace(/[^a-z0-9-_]/g,'').slice(0,80)||null,custom_domain:String(d.custom_domain||'').trim().slice(0,200)||null,existing_website:String(d.existing_website||'').trim().slice(0,500)||null,feature_package:String(d.feature_package||'').trim().slice(0,150)||null,project_details:String(d.project_details).trim().slice(0,5000),status:'New'});sendJson(res,201,{ok:true,reference})}catch(e){console.error(e);sendJson(res,500,{error:'The request could not be saved.'})}}
async function health(res,details){const started=Date.now();try{const result=await db(REQUESTS+'?select=id',{headers:{Prefer:'count=exact'},method:'HEAD'});const count=Number((result.headers.get('content-range')||'*/0').split('/')[1])||0;const data={status:'healthy',timestamp:new Date().toISOString(),service:'TalonDNS',environment:process.env.VERCEL_ENV||'development',supabase:{connected:true,table:REQUESTS,requestCount:count,responseTimeMs:Date.now()-started}};if(details)data.adminUsers={table:USERS};return sendJson(res,200,data)}catch(e){return sendJson(res,503,{status:'unhealthy',timestamp:new Date().toISOString(),service:'TalonDNS',supabase:{connected:false,table:REQUESTS,configured:Boolean(process.env.SUPABASE_URL&&process.env.SUPABASE_SERVICE_ROLE_KEY),error:e.message}})}}

export default async function handler(req,res){
  const u=new URL(req.url,'http://'+req.headers.host),path=u.pathname.toLowerCase().replace(/\/$/,'')||'/';
  if(req.method==='GET'&&redirects[path]){res.writeHead(308,{Location:redirects[path]});return res.end()}
  if(path==='/'&&req.method==='GET')return send(res,200,'text/html; charset=utf-8',publicPage());
  if(path==='/health'&&req.method==='GET')return health(res,false);
  if(path==='/health/details'&&req.method==='GET')return health(res,true);
  if(path==='/api/requests'&&req.method==='POST')return createRequest(req,res);
  const current=session(req);
  if(path==='/admin'&&req.method==='GET')return send(res,200,'text/html; charset=utf-8',current?adminPage(current):loginPage());
  if(path==='/admin/login'&&req.method==='POST'){try{const d=await body(req),username=String(d.username||'').trim().toLowerCase();const users=(await db('rpc/authenticate_admin','POST',{p_username:username,p_password:String(d.password||'')})).data||[];const user=users[0];if(!user)return send(res,401,'text/html; charset=utf-8',loginPage('Incorrect username or password.'));res.writeHead(302,{Location:'/admin','Set-Cookie':'talondns_admin='+makeToken(user)+'; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200'});return res.end()}catch(e){console.error(e);return send(res,500,'text/html; charset=utf-8',loginPage('Login is unavailable. Run the database migration.'))}}
  if(path==='/admin/logout'){res.writeHead(302,{Location:'/admin','Set-Cookie':'talondns_admin=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});return res.end()}
  if(path==='/api/admin/requests'&&req.method==='GET'){if(!current)return sendJson(res,401,{error:'Unauthorized'});try{return sendJson(res,200,(await db(REQUESTS+'?select=*&order=created_at.desc')).data)}catch(e){return sendJson(res,500,{error:'Unable to load requests'})}}
  const rm=path.match(/^\/api\/admin\/requests\/([0-9a-f-]+)$/);if(rm&&req.method==='PATCH'){if(!canEdit(current))return sendJson(res,403,{error:'Insufficient permission'});try{const d=await body(req);if(!STATUSES.includes(d.status))return sendJson(res,400,{error:'Invalid status'});await db(REQUESTS+'?id=eq.'+encodeURIComponent(rm[1]),'PATCH',{status:d.status,updated_at:new Date().toISOString()});return sendJson(res,200,{ok:true})}catch(e){return sendJson(res,500,{error:'Unable to update request'})}}
  if(path==='/api/admin/users'&&req.method==='GET'){if(!isOwner(current))return sendJson(res,403,{error:'Owner access required'});return sendJson(res,200,(await db(USERS+'?select=id,username,display_name,role,active,created_at,last_login_at&order=created_at.asc')).data)}
  if(path==='/api/admin/users'&&req.method==='POST'){if(!isOwner(current))return sendJson(res,403,{error:'Owner access required'});try{const d=await body(req),username=String(d.username||'').trim().toLowerCase();if(!username||String(d.password||'').length<12||!ROLES.includes(d.role))return sendJson(res,400,{error:'Username, 12-character password, and valid role are required'});await db('rpc/create_admin_user','POST',{p_username:username,p_display_name:String(d.display_name||username).trim(),p_password:String(d.password),p_role:d.role});return sendJson(res,201,{ok:true})}catch(e){return sendJson(res,400,{error:e.message.includes('duplicate')?'Username already exists':e.message})}}
  const um=path.match(/^\/api\/admin\/users\/([0-9a-f-]+)$/);if(um&&req.method==='PATCH'){if(!isOwner(current))return sendJson(res,403,{error:'Owner access required'});if(um[1]===current.id)return sendJson(res,400,{error:'You cannot disable your own account'});const d=await body(req);await db(USERS+'?id=eq.'+encodeURIComponent(um[1]),'PATCH',{active:Boolean(d.active),updated_at:new Date().toISOString()});return sendJson(res,200,{ok:true})}
  send(res,404,'text/plain; charset=utf-8','Not Found');
}
