import crypto from 'node:crypto';
import appHandler from './app.js';

const PREVIEWS='site_previews';
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const send=(res,status,type,body,headers={})=>{res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store',...headers});res.end(body)};
const sendJson=(res,status,data)=>send(res,status,'application/json; charset=utf-8',JSON.stringify(data));
function cfg(){if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw Error('Supabase is not configured');return{url:process.env.SUPABASE_URL.replace(/\/$/,''),key:process.env.SUPABASE_SERVICE_ROLE_KEY}}
async function db(path,method='GET',payload){const{url,key}=cfg();const r=await fetch(url+'/rest/v1/'+path,{method,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',Prefer:'return=representation'},body:payload?JSON.stringify(payload):undefined});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text||null}if(!r.ok)throw Error(data?.message||data?.error||'Database request failed');return data}
async function body(req){let raw='';for await(const c of req){raw+=c;if(raw.length>8000000)throw Error('Request too large')}return raw?JSON.parse(raw):{}}
function session(req){const secret=process.env.ADMIN_SESSION_SECRET||'';const value=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('talondns_admin='))?.slice(15);if(!value||!secret)return null;const[payload,sig]=value.split('.');if(!payload||!sig)return null;const expected=crypto.createHmac('sha256',secret).update(payload).digest('base64url');try{if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const data=JSON.parse(Buffer.from(payload,'base64url').toString());return data.exp>Date.now()?data:null}catch{return null}}
const canEdit=u=>u&&['owner','admin'].includes(u.role);

function captureResponse(){let status=200,headers={},chunks=[];return{writeHead(code,h={}){status=code;headers={...headers,...h}},setHeader(k,v){headers[k]=v},getHeader(k){return headers[k]},end(chunk=''){if(chunk)chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(String(chunk)))},result(){return{status,headers,body:Buffer.concat(chunks).toString('utf8')}}}}

const footerCss=`<style>
.td-footer{width:min(1180px,calc(100% - 32px));margin:56px auto 0;padding:38px 0 22px;border-top:1px solid #29415e;color:#f4f8ff}.td-footer-grid{display:grid;grid-template-columns:1.2fr .8fr 1.4fr;gap:28px}.td-footer h3{margin:0 0 12px}.td-footer p,.td-footer li{color:#aebfd3;line-height:1.6}.td-footer ul{margin:0;padding-left:18px}.td-footer a{color:#9edfff}.td-preview-list{display:grid;gap:12px}.td-preview-card{display:grid;grid-template-columns:150px 1fr;gap:16px;padding:14px;border:1px solid #29415e;border-radius:15px;background:#081524;text-decoration:none;color:inherit}.td-preview-card img{width:150px;height:92px;object-fit:cover;border-radius:10px;background:#030c17}.td-placeholder{width:150px;height:92px;display:grid;place-items:center;border-radius:10px;background:linear-gradient(135deg,#102640,#16385b);font-weight:850}.td-copy{margin-top:28px;padding-top:18px;border-top:1px solid #29415e;display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;color:#aebfd3}@media(max-width:900px){.td-footer-grid{grid-template-columns:1fr 1fr}.td-footer-grid>div:first-child{grid-column:1/-1}}@media(max-width:700px){.td-footer-grid{grid-template-columns:1fr}.td-footer-grid>div:first-child{grid-column:auto}.td-preview-card{grid-template-columns:105px 1fr}.td-preview-card img,.td-placeholder{width:105px;height:74px}}
</style>`;
function footer(previews){const items=previews.length?previews:[{title:'Los Santos Property Services',description:'A complete FiveM business site and operations portal built for LSPS.',site_url:'/lsps',image_data:null}];return`${footerCss}<footer class="td-footer"><div class="td-footer-grid"><div><h3>TalonDNS</h3><p>Professional websites, custom domains, employee portals, and business management systems built specifically for FiveM businesses and communities.</p><p><a href="#register">Request service</a> · <a href="/lsps">View LSPS</a> · <a href="/admin">Admin login</a></p></div><div><h3>Services</h3><ul><li>Custom business websites</li><li>Employee and application portals</li><li>Vehicle inventories</li><li>Property listings</li><li>TalonDNS short links</li></ul></div><div><h3>Featured Projects</h3><div class="td-preview-list">${items.map(x=>`<a class="td-preview-card" href="${esc(x.site_url||'#')}">${x.image_data?`<img src="${esc(x.image_data)}" alt="${esc(x.title)} preview">`:'<div class="td-placeholder">Site Preview</div>'}<div><strong>${esc(x.title)}</strong><p>${esc(x.description||'View this TalonDNS project.')}</p><span>Visit site →</span></div></a>`).join('')}</div></div></div><div class="td-copy"><span>© ${new Date().getFullYear()} TalonDNS. All rights reserved.</span><span>Built for FiveM businesses.</span></div></footer>`}

function previewsPage(user){return`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Site Previews · TalonDNS</title><style>:root{color-scheme:dark;--panel:#0d1c30;--line:#29415e;--text:#f4f8ff;--muted:#aebfd3}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;color:var(--text);background:linear-gradient(150deg,#040912,#081524 52%,#050b14)}main{width:min(1050px,calc(100% - 32px));margin:auto;padding:30px 0 60px}header{display:flex;justify-content:space-between;align-items:center;gap:16px;padding-bottom:20px;border-bottom:1px solid var(--line)}a{color:#9edfff}.card{padding:22px;border:1px solid var(--line);border-radius:16px;background:var(--panel);margin-top:20px}form{display:grid;gap:13px}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:grid;gap:7px}input,textarea{width:100%;padding:11px;border:1px solid #36516f;border-radius:10px;color:white;background:#030c17;font:inherit}textarea{min-height:100px}button{min-height:44px;padding:0 18px;border:0;border-radius:11px;background:#42c7ff;color:#03101c;font-weight:850;cursor:pointer}.danger{background:#ff6b6b}.status{display:none;padding:12px;border-radius:10px}.status.ok{display:block;background:#74e3a314}.status.error{display:block;background:#ff505014}.preview{display:grid;grid-template-columns:190px 1fr auto;gap:16px;align-items:center}.preview img{width:190px;height:108px;object-fit:cover;border-radius:10px}.meta{color:var(--muted)}@media(max-width:700px){.row,.preview{grid-template-columns:1fr}.preview img{width:100%;height:auto}}</style></head><body><main><header><div><h2>Site Previews</h2><div class="meta">Signed in as ${esc(user.display_name||user.username)}</div></div><div><a href="/admin">Admin</a> · <a href="/">Homepage</a></div></header><section class="card"><h3>Add a preview</h3><form id="form"><div class="row"><label>Site title<input name="title" required></label><label>Site URL<input name="site_url" value="/lsps" required></label></div><label>Description<textarea name="description" required></textarea></label><label>Preview image<input id="image" type="file" accept="image/png,image/jpeg,image/webp" required></label><label><span><input type="checkbox" name="active" checked> Show on homepage</span></label><div class="meta">Maximum image size: 4 MB. The image is stored in Supabase as a data URL.</div><button>Save preview</button><div id="status" class="status"></div></form></section><div id="list"></div></main><script>
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function readFile(file){return new Promise((resolve,reject)=>{if(!file)return reject(Error('Choose an image'));if(file.size>4000000)return reject(Error('Image must be 4 MB or smaller'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Unable to read image'));r.readAsDataURL(file)})}
async function load(){const target=document.getElementById('list');target.innerHTML='<p>Loading...</p>';const r=await fetch('/api/admin/previews'),a=await r.json();if(!r.ok){target.innerHTML='<p>'+h(a.error)+'</p>';return}target.innerHTML=a.map(x=>'<article class="card preview"><img src="'+h(x.image_data)+'" alt=""><div><h3>'+h(x.title)+'</h3><div class="meta">'+h(x.site_url)+' · '+(x.active?'Visible':'Hidden')+'</div><p>'+h(x.description||'')+'</p></div><button class="danger" data-id="'+h(x.id)+'">Delete</button></article>').join('')||'<p>No previews yet.</p>';target.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this preview?'))return;await fetch('/api/admin/previews/'+b.dataset.id,{method:'DELETE'});load()})}
document.getElementById('form').onsubmit=async e=>{e.preventDefault();const st=document.getElementById('status');try{const data=Object.fromEntries(new FormData(e.target));data.active=e.target.elements.active.checked;data.image_data=await readFile(document.getElementById('image').files[0]);const r=await fetch('/api/admin/previews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),d=await r.json();if(!r.ok)throw Error(d.error);st.className='status ok';st.textContent='Preview saved';e.target.reset();e.target.elements.active.checked=true;load()}catch(err){st.className='status error';st.textContent=err.message}};load();
</script></body></html>`}

async function renderOriginal(req,res,transform){const proxy=captureResponse();await appHandler(req,proxy);const out=proxy.result();let content=out.body;if(transform&&String(out.headers['Content-Type']||out.headers['content-type']||'').includes('text/html'))content=await transform(content);send(res,out.status,out.headers['Content-Type']||out.headers['content-type']||'text/plain; charset=utf-8',content,Object.fromEntries(Object.entries(out.headers).filter(([k])=>k.toLowerCase()!=='content-type')))}

export default async function handler(req,res){
  const path=new URL(req.url,'http://'+req.headers.host).pathname.toLowerCase().replace(/\/$/,'')||'/';
  if(path==='/'&&req.method==='GET')return renderOriginal(req,res,async html=>{let previews=[];try{previews=await db(PREVIEWS+'?select=title,description,site_url,image_data&active=eq.true&order=sort_order.asc,created_at.asc')||[]}catch{}return html.replace('</body>',footer(previews)+'</body>')});
  if(path==='/admin'&&req.method==='GET')return renderOriginal(req,res,async html=>session(req)?html.replace('<div class="tabs">','<div class="tabs"><a class="tab" href="/admin/previews" style="text-decoration:none">Site Previews</a>'):html);
  if(path==='/admin/previews'&&req.method==='GET'){const current=session(req);if(!current){res.writeHead(302,{Location:'/admin'});return res.end()}return send(res,200,'text/html; charset=utf-8',previewsPage(current))}
  if(path==='/api/admin/previews'&&req.method==='GET'){if(!session(req))return sendJson(res,401,{error:'Unauthorized'});try{return sendJson(res,200,await db(PREVIEWS+'?select=*&order=sort_order.asc,created_at.asc'))}catch{return sendJson(res,500,{error:'Unable to load previews. Run the site_previews migration.'})}}
  if(path==='/api/admin/previews'&&req.method==='POST'){const current=session(req);if(!canEdit(current))return sendJson(res,403,{error:'Insufficient permission'});try{const d=await body(req),image=String(d.image_data||'');if(!String(d.title||'').trim()||!String(d.site_url||'').trim()||!image.startsWith('data:image/'))return sendJson(res,400,{error:'Title, URL, and image are required'});if(image.length>5600000)return sendJson(res,400,{error:'Image is too large'});await db(PREVIEWS,'POST',{title:String(d.title).trim().slice(0,150),description:String(d.description||'').trim().slice(0,1000),site_url:String(d.site_url).trim().slice(0,500),image_data:image,active:d.active!==false,sort_order:0});return sendJson(res,201,{ok:true})}catch{return sendJson(res,500,{error:'Unable to save preview. Run the site_previews migration.'})}}
  const match=path.match(/^\/api\/admin\/previews\/([0-9a-f-]+)$/);if(match&&req.method==='DELETE'){const current=session(req);if(!canEdit(current))return sendJson(res,403,{error:'Insufficient permission'});try{await db(PREVIEWS+'?id=eq.'+encodeURIComponent(match[1]),'DELETE');return sendJson(res,200,{ok:true})}catch{return sendJson(res,500,{error:'Unable to delete preview'})}}
  return appHandler(req,res);
}
